### ISSUE TITLE
Headers workaround

### ISSUE THREAD

**Issue by paparga** [domdere/cassava-conduit#26]
Hi,
What is the best workaround for creating headers?

Thanks

**Comment by paparga** [comment]
I made my first attempt using ScopedTypeVariables , any feedback is welcome

``` haskell
toDefaultOrderedByName
  :: forall m a . (Monad m, ToRecord a, DefaultOrdered a, ToNamedRecord a)
  -> EncodeOptions
  => ConduitT a ByteString m ()
toDefaultOrderedByName opts = go False
  where
    go True = toCsv opts
    go False  = do
      yield $ encodeHeader []
      go True

    encodeHeader :: [a] -> ByteString
    encodeHeader = BSL.toStrict . encodeDefaultOrderedByName

```

**Comment by domdere** [comment]
I usually just write the header to the handle before beginning the streaming.

The header only appears once at the top of the file, it doesnt make sense to "stream" it

**Comment by paparga** [comment]
That made a lot of sense, thanks!
