### ISSUE TITLE
Add headers variant redux

### ISSUE THREAD

**Issue by ParetoOptimalDev** [domdere/cassava-conduit#30]
I have a source that doesn't support being treated like a filehandle, nor does it support being updated after "writing the file" so to speak.

I noticed discussion in #28 about using multiple producers and  slightly modified some code from there:

```haskell
toNamedDefaultOrderCsv :: (Monad m, ToNamedRecord a, DefaultOrdered a) => EncodeOptions -> ConduitT a BS.ByteString m ()  
toNamedDefaultOrderCsv opts = {-# SCC toCsv_p #-} map $ BSL.toStrict . encodeDefaultOrderedByNameWith opts . pure  
```

The problem is this prints a header per line which I think you allude to in one of your longer comments on #28.

So then... I think I'll be perfectly fine if I can just specify a string to be prepended before all other lines and saw your comment about multiple producers. I came up with this:

```haskell
runConduit $ sequenceSources [ yieldMany [ Left ()], yieldMany [ Right "a", Right "b" ]]
  .|  concat
  .| (awaitForever $ \x ->
         case x of Left () ->
                     liftIO (putStrLn "hi")
                     Right _ -> yield x)
  .| printC
```

This only prints out:

```
hi
Right "a"
```

I can of course use an IORef to do this, but I'd prefer to make the multiple sources approach work. I think it would be a good addition here as well.

**Comment by domdere** [comment]
ok, is there any reason you can just do the equivalent to the `putStrLn "hi"` line *before* running the conduit? like it seems a bit weird to use a streaming thing to do a one off bounded operation, so like:

``` haskell
do
    purStrLn "hi" -- normal one off IO operation for header
    runConduit ... -- run the conduit for the potentially known number of write operations you want to run with bounded memory 
```

**Comment by domdere** [comment]
you do say you can only "write to the file once" but by that do you mean you can only flush once (and hence you cant do what i am suggesting above)?

if thats the case though you may still have a problem as the conduit flushes on every so many lines, thats how it works in the bounded memory footprint

**Comment by ParetoOptimalDev** [comment]
I have a consumer later in my pipeline that:

- is a remote service without any sort of handle like interface 
- needs the header
- can be only written as a multipart upload once and not be updated

Basically I'm forced to make this work:

```haskell
someDataSource
.| toCsv
.| uploadMultipartWithHeader
```

Also, I can't accumulate the file contents and do actually need streaming here, or I'd just prepend to the accumulated bytestring.

I can't do what is suggested above because `uploadMultipartWithHeader` needs the header.
