### ISSUE TITLE
Relax upper bounds on bytestring, possibly text

### ISSUE THREAD

**Issue by pbrisbin** [domdere/cassava-conduit#31]
The package is compiling fine in our project with `lts-20.2` and `allow-newer: true`, so I suspect it's just a bounds revision that's needed. Could you relax those so we can remove the `allow-newer: true`?

For reference, https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L6108-L6109

**Comment by nineonine** [comment]
that would be great.
I can offer a patch if necessary?

**Comment by domdere** [comment]
sure, patches welcome!
