### ISSUE TITLE
Uploading to Stackage?

### ISSUE THREAD

**Issue by mstksg** [domdere/cassava-conduit#8]
Hi!  Thanks for the great package, it's been very useful to me! :D Just wondering if there any plans to put cassava-conduit onto the [stackage](https://www.stackage.org/) package database?

(If you wanted to, it's as simple as [editing this file](https://github.com/fpco/stackage/edit/master/build-constraints.yaml))

**Comment by domdere** [comment]
Didnt have plans for it no, but not averse to the idea, dont want to get in anyones way

**Comment by mstksg** [comment]
For the most part, you just drop it into the file and can forget about it!  If the haskell ecosystem ever moves past your package (like, say, breaking changes in the cassava or conduits library), your package would just drop from the nightly snapshots until you update it.

**Comment by mstksg** [comment]
fwiw, the latest version on hackage builds/solves fine with the latest stackage snapshots.

**Comment by domdere** [comment]
> For the most part, you just drop it into the file and can forget about it!

ok cool will do then

**Comment by domdere** [comment]
https://github.com/fpco/stackage/pull/1714

**Comment by domdere** [comment]
(sorry i took so long)

**Comment by mstksg** [comment]
Thanks! And no worries at all :)

**Comment by domdere** [comment]
its up now
